#include <stdio.h>

int main() {
    printf("\033[1;34m");
    printf("I hope one day you will find your passion in tekkom and know what you like\n");
    printf("\033[0m");

    printf("Kalau udah sukses jangan lupain aslab kalian ya :( \n");
    printf("ID Lines aslabs 23: \n CH: christianhadiwijaya \n DS: daffsf \n MF: macropp\n JD: jesayadavidp\n BH: bnhrd\n\n");

    printf("From: Joshua Richardo Riangkamang\n");
    printf("Hai Josh, jika kamu melihat ini, berarti kamu berhasil menyelesaikan hal perkuliahan ini. Selamat yaaa, dahulu kamu pernah stress karena matkul Kalkulus, Fislis, RL, dan lain-lain. Tapi sekarang kamu telah membuktikan kepada dirimu, bahwa kamu itu bisa, kamu itu mampu, dan kamu itu hebat. Oh ya, ingat selalu ya, semua itu juga bukan hanya karena usahamu tapi karena pertolongan Tuhan. Di saat kamu sedang sendiri dan hatimu hancur, Tuhan mengangkat kamu kembali. Jangan lupakan juga teman-teman mu yang menemanimu, mereka juga menjadi salah satu faktor kamu masih ada sampai sekarang. Sayangi selalu orangtuamu, dan adikmu, karena merekalah kamu masih berjuang. Tetap ingat, bahwa tidak ada yang abadi di dunia ini, jangan kejar uang, kejarlah kesuksesan dalam menjadi orang yang berguna untuk masyarakat. Ingat bahwa ketika kamu menulis ini, kamu mempunyai tujuan besar untuk menjadi orang yang sukses, orang yang berguna, orang yang berbakti terhadap masyarakat dan keberlangsungan generasi manusia. Oh ia, ketika kamu menulis ini, kamu juga mempunyai sebuah mindset bahwa kamu tidak akan menikah, aku sekarang jadi penasaran apakah kamu benar-benar akan tidak menikah? atau kamu telah menemukan seseorang yang tepat, yang bisa menggantikan sih A... KWKWKWKWK... Tapi gapapa kok Josh, kejarlah selalu yang terbaik untuk dirimu dan untuk sesamamu. Oh yaa, sesusah-susahnya kamu di masa mendatang, jangan pernah ada niatan untuk mengakhiri hidup yaa, hidup itu indah tau. Kesusahan kamu itu hanya sementara saja, masih banyak kebahagiaan di depan yang menanti kamu. Kalau memang bisa, eksplore lah dunia ini sesuai cita-cita awal kamu, dan ingat selalu, bahwa anugerah ternikmat di dunia ini adalah makan wkkwkwkw. Btw ketika kamu menulis ini, kamu belum bisa moveon sepenuhnya dari V. Dia memang bukan tipe kamu, tapi kamu dulunya nyaman bgt ama dia, dan tetap ingatlah dulu kalian pernah se-``dekat`` itu WKKWKWKWK. Ya pokonya kejarlah cita-cita kamu, ingat tujuan hidup kamu, bahagiakan diri kamu, bahagiakan keluar mu, bahagiakan orang di sekitar kamu... Semangat terus Josh, perjalanan yang panjang telah dimulai...");
    printf("\n\nKost Unihome, Depok, 16 Mei 2025");
}